services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crime_analytics
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: cdia-elasticsearch
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: test
      xpack.security.enabled: true
      node.name: es01
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

#  ingestion-service:
#    image: openjdk:21-jdk
#    container_name: ingestion-service
#    depends_on:
#      - postgres
#      - elasticsearch
#    ports:
#      - "8080:8080"
#    working_dir: /app
#    command: [ "java", "-jar", "/app/ingestion-service.jar" ]
#    volumes:
#      - ../ingestion-service/target/ingestion-service.jar:/app/ingestion-service.jar
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crime_analytics
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  flink-jobmanager:
    image: flink:1.20-scala_2.12-java17
    container_name: flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"  # RPC
    command: jobmanager
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
      interval: 5s
      retries: 20

  flink-taskmanager:
      image: flink:1.20-scala_2.12-java17
      container_name: flink-taskmanager
      depends_on:
        - flink-jobmanager
      environment:
        - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      command: taskmanager

#  processing-service:
#    build: ./processing-service
#    container_name: processing-service
#    depends_on:
#      flink-jobmanager:
#        condition: service_healthy
#      flink-taskmanager:
#        condition: service_started
#    environment:
#      FLINK_JOBMANAGER_HOST: flink-jobmanager
#      FLINK_JOBMANAGER_RPC_PORT: 6123