server:
  port: 8081

spring:
  application:
    name: ingestion-service

  datasource:
    url: jdbc:postgresql://localhost:5432/crime_analytics
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to "validate" in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info