server:
  port: 8083

spring:
  application:
    name: search-service

  elasticsearch:
    uris: http://localhost:9200

management:
  endpoints:
    web:
      exposure:
        include: health,info
