server:
  port: 8085

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://cdia-elasticsearch:9200
    username: elastic
    password: test
    connection-timeout: 5s
    socket-timeout: 30s

logging:
  level:
    org.springframework.data.elasticsearch: INFO
    co.elastic.clients: WARN
    org.springframework.data.elasticsearch.core: DEBUG
    org.springframework.data.elasticsearch.repository: DEBUG
